# Generated by Django 5.0.6 on 2024-06-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cart_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
